# Pod user with userns set to "node" mode.
apiVersion: v1
kind: Pod
metadata:
  name: pod-userns-node
  namespace: default
  annotations:
    alpha.kinvolk.io/userns: "node"
spec:
  restartPolicy: Never
  containers:
  - name: pod-userns
    image: busybox
    command: ["sh"]
    args: ["-c", "sleep infinity"]
