# Pod user with userns set to "pod" mode. Pod creation would fail if userns
# not supported by runtime.
apiVersion: v1
kind: Pod
metadata:
  name: pod-userns-pod
  namespace: default
  annotations:
    alpha.kinvolk.io/userns: "pod"
spec:
  restartPolicy: Never
  containers:
  - name: pod-userns
    image: ubuntu
    command: ["sh"]
    args: ["-c", "sleep infinity"]
