apiVersion: v1
kind: Pod
metadata:
  name: pod-userns
  namespace: default
  annotations:
    alpha.kinvolk.io/userns: "pod"
spec:
  restartPolicy: Never
  containers:
  - name: pod-userns
    image: busybox
    command: ["sh"]
    args: ["-c", "sleep infinity"]
#  hostNetwork: true
    volumeMounts:
    - name: config-volume
      mountPath: /etc/userns-cm1/content
    - name: config-volume-with-0777
      mountPath: /etc/userns-cm2/content
    env:
      - name: SPECIAL_LEVEL_KEY
        valueFrom:
          configMapKeyRef:
            name: userns-cm
            key: content
  volumes:
    - name: config-volume
      configMap:
        name: userns-cm
    - name: config-volume-with-0777
      configMap:
        name: userns-cm
        defaultMode: 0777
