# Pod user with userns set to "pod" mode. Pod creation would fail if userns
# not supported by runtime.
apiVersion: v1
kind: Pod
metadata:
  name: pod-userns-pod
  namespace: default
  annotations:
    alpha.kinvolk.io/userns: "pod"
spec:
#  securityContext:
#    runAsUser: 1000
  restartPolicy: Never
  containers:
  - name: pod-userns
    image: busybox
    command: ["sh"]
    args: ["-c", "sleep infinity"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/userns-cm/content
  volumes:
    - name: config-volume
      configMap:
        name: test-config-map
