apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: prestop
  name: prestop
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prestop
  template:
    metadata:
      annotations:
        alpha.kinvolk.io/sidecar-rata-1: "dummy"
        alpha.kinvolk.io/sidecar-rata-2: "dummy"
      labels:
        run: prestop
    spec:
      containers:
      - image: rodrigocampos/signal-tests:v0.1-test1
        imagePullPolicy: Always
        command: ["/app/app"]
        name: rata-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "(echo rata-1; echo $(date); echo Going to sleep; sleep 10; echo After sleep) > /tmp/rata; exit 0" ]
      - image: rodrigocampos/signal-tests:v0.1-test1
        imagePullPolicy: Always
        command: ["/app/app"]
        name: rata-2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "(echo rata-2; echo $(date); echo Going to sleep; sleep 10; echo After sleep) > /tmp/rata; exit 0" ]

      - command:
        - sleep
        - infinity
        image: debian
        imagePullPolicy: Always
        name: debian-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "(echo debian-1; echo $(date); echo Going to sleep; sleep 10; echo After sleep) > /tmp/rata; exit 0" ]
      - command:
        - sleep
        - infinity
        image: debian
        imagePullPolicy: Always
        name: debian-2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "(echo debian-2; echo $(date); echo Going to sleep; sleep 10; echo After sleep) > /tmp/rata; exit 0" ]
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
