# Pod without the userns annotation and with special features that would cause
# the user namespace support to be disabled.
apiVersion: v1
kind: Pod
metadata:
  name: pod-userns-default-special
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: pod-simple
    image: busybox
    command: ["sh"]
    args: ["-c", "sleep infinity"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/userns-cm/content
  volumes:
    - name: config-volume
      configMap:
        name: test-config-map
  # TODO: add more special features here.
  hostNetwork: true